version: '3.1'

services:

 wordpress:
   image: dagman62/apache-wordpress 
   networks:
     - apache_mysql 
   restart: always
   container_name: wordpress
   links:
    - mysql
   ports:
    - "8080:80"
   environment:
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_NAME: wordpress
     WORDPRESS_DB_PASSWORD: "wordpress"
     WORDPRESS_DB_HOST: mysql 
     MYSQL_PORT_3306_TCP: 3306
   volumes:
     - apache_log_volume:/usr/local/apache/logs

 mysql:
   image: mysql
   networks:
     - apache_mysql
   restart: always
   container_name: mysql
   environment:
     MYSQL_ROOT_PASSWORD: "wordpress"
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: "wordpress"
   volumes:
     - mysql_data_volume:/var/lib/mysql

networks:
  apache_mysql:
volumes:
  apache_log_volume:
  mysql_data_volume:
